### PR TITLE
Update .gitignore and fix formatting

### PR DESCRIPTION
**Pull request by friederbluemle**
This updates .gitignore to ignore Gradle build output, and fixes all whitespace errors in the repo.

<sub><sup>Once approved, please use a *normal* GitHub merge (i.e. **NO rebase/squash** merge) to integrate the commit(s) from the branch of this pull request. The changes are broken up into meaningful, [atomic commits](https://www.freshconsulting.com/atomic-commits/), and my branch should already be up-to-date with the latest target branch. If it isn't, or if you'd like me to combine/split commits, please let me know, and I will make the necessary updates as soon as possible. Thank you!</sup></sub>

### CODE REVIEW

**Comment by handmadecode** [comment]
Thanks for the pull request. The whitespace and .gitignore changes look fine.

Any particular reason you want to build with gradle 2.13? My plan is to move to Gradle 4 and drop support for older versions in the near future.

**Comment by friederbluemle** [comment]
@handmadecode - Very good question. I actually have a separate local work-in-progress branch where I updated Gradle to the latest version `4.10.2` - However, the reason I did not include it here is that any Gradle version _higher_ than `2.13` contains a breaking change which will cause the build to fail (you can try by just using version `2.14`). There are likely other incompatibilities in newer versions, and I wanted to keep this first PR small. Version `2.13` works _without changing any of the build logic_, which is why I thought we could go with this interim version for now. If you prefer to exclude it, or move it so a separate PR, I can definitely do that. Please let me know.

BTW thanks for these amazing Gradle plugins! They're so useful, especially the updated jdepend plugin. I'm planning to try others as well. 👍

**Comment by handmadecode** [comment]
Good to hear that the plugins are useful to you.

I'd be happy to accept the whitespace and .gitignore changes, could you please make a new pull request with those two commits and use the _development_ branch as base branch? (I've changed the project settings so this should be the default now)

As for upgrading the wrapper to 2.13, I'm not convinced that it adds any substantial value. Or do you see any improvement in building the project using v2.13?

**Comment by friederbluemle** [comment]
Sure, I've removed the Gradle wrapper update from this PR and changed the base branch to `development` - No need for a new PR :)

Regarding the 2.13 update: Looking at some of the [Release Notes](https://gradle.org/releases/) between 2.2.1 (the current version) and 2.13 it does appear there are some significant performance and other improvements (the two releases are 1.5 years apart!) But of course if the update to the latest version is straightforward and can be done quickly, then moving to the latest would be best. I'll be moving the commit to a separate commit/PR, and we can discuss/test over there.

**Pull request merged**
